name: Main Branch CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}

      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - run: npm install
    - run: npm run build
    - run: npm run test

    - name: Bump version
      uses: anothrNick/github-tag-action@1.19.0
      id: version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false
        DEFAULT_BUMP: patch
        DRY_RUN: true
      
    - name: Generate changelog
      id: changelog
      uses: metcalfc/changelog-generator@v0.2.3
      with:
        myToken: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        tag_name: v${{ steps.version.outputs.new_tag }}
        body: ${{ steps.changelog.outputs.changelog }}
        draft: false
        prerelease: false

